/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "GltfAnalysisAgentSfn": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "ValidateGltfFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "gltf-validation": {
      "name": string
      "type": "sst.aws.Function"
    }
    "gltfAgentUi": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "gltfStorage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}